### PR TITLE
Updated personal.html and main.css with styling

### PR DESCRIPTION
**Pull request by ColleenWoolsey**
1. 'git fetch --all'
1. 'git checkout personal2'
1. 'Make sure personal.html and main.css additions are ok'

### CODE REVIEW

**Review by jdbbaugh — APPROVED** [review]
awesome like bowie!

**Review by loetek — APPROVED** [review]
The syntax looks great!

**Review by loetek — APPROVED** [review]
Awesome!!

**Review by asiamcarter — APPROVED** [review]
looks great!

**Pull request merged**
